# my-test-project/docker-compose.yml
version: "3.9"
services:
  nginx:
    # build: ./docker/nginx
    image: 729581434105.dkr.ecr.us-east-1.amazonaws.com/laravel-on-ecs-dzg-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    # build: ./docker/php
    image: 729581434105.dkr.ecr.us-east-1.amazonaws.com/laravel-on-ecs-dzg-php:latest
    volumes:
      - proxysql-sock:/var/lib/proxysql
    depends_on:
      - proxysql

  proxysql:
    # build: ./docker/proxysql
    image: 729581434105.dkr.ecr.us-east-1.amazonaws.com/laravel-on-ecs-dzg-proxysql:latest
    volumes:
      - proxysql-sock:/var/lib/proxysql
      - ./docker/proxysql/proxysql.cnf.template:/etc/proxysql.cnf.template
    environment:
      - BACKEND_TIDB_HOST=host.docker.internal
      - BACKEND_TIDB_PORT=4000
      - BACKEND_TIDB_USER=tidb
      - BACKEND_TIDB_PASS=tidb_password
      - BACKEND_AURORA_HOST=host.docker.internal
      - BACKEND_AURORA_PORT=62246 
      - BACKEND_AURORA_USER=aurora
      - BACKEND_AURORA_PASS=aurora_password
volumes:
  proxysql-sock:
